### ISSUE TITLE
TimeoutException when using Slave ID other than 1

### ISSUE THREAD

**Issue by Pratched** [SciFiDryer/ModbusMechanic#12]
I am trying to add functionality to my communication (as the master) with inverters (the slaves) via a corporate Modbus implementation (from SMA Solar Technologies), without actually connecting to the hardware all the time. Id hoped, that this tool might ease things for me.

However so far, I could not even get it to run with itself. 
I thought I tried the simpliest queries I already managed to implement in my own communication. 
Reading Input Registers with FunctionCode _0x04_ at Register _30843_. _Unsigned32_ (2 Registers) at SlaveID _3_ and of course ProtocolID _0_.

But all I got is a TimeoutException (see screenshot below).
Is there anything I could check or read up on to figure out where things went wrong?

PS: I am running a Debian Bookworm system with OpenJDK 17.0.5+8-2 using Hotspot JIT. Maybe I should mention, that if I am running the .jar without `sudo` and trying to connect to 127.0.0.1 it says `java.net.ConnecException: Connection Refused`.

![image](https://user-images.githubusercontent.com/19487828/213157848-cc6ec2b6-fff7-45ca-ad63-d7855f081015.png)

**Comment by SciFiDryer** [comment]
Usually this situation arises when the application is run without privileges to bind to port 502 or another application has already bound itself. You can start the application with the debug argument "java -jar ModbusMechanic.jar -debug" from the ModbusMechanic directory to see verbose debugging information. Another helpful command to run is "netstat -an" to see if anything is listening on port 502. Look for LISTENING on the netstat list under port 502.

If another application has already bound itself to port 502, ModbusMechanic will not be able to start a TCP slave simulator. You may have already tried this but can you connect to your Ethernet or WiFi IP?

Iptables or firewall rules can also cause packets to be dropped. I like to use tcpdump for verifying packet flow.

**Comment by Pratched** [comment]
Thanks for your quick response. 

So I tried with `-debug`, of course again with `sudo` and it just says, that no bytes have been received. 
![image](https://user-images.githubusercontent.com/19487828/213454151-2fad2b9e-e0d8-4b62-ae00-da4b5fc6e149.png)

I tried (with root privileges) `natstat -an | grep 502` respectively `natstat -an | grep LISTENING`, neither show any significant entrys.

When you say connecting to WiFi or Ethernet IP you mean trying to enter my wifi interface's , i.e. `inet 192.168.178.68` in the IP field within ModbusMechanic?

**Comment by SciFiDryer** [comment]
I was able to reproduce this exact error and it turns out there was a typo in my code. The slave ID was hardcoded to always be 1 so it was not answering on 3. This is now fixed in 06df4d7 and version 2.4 which is now available. Thanks for your feedback and data, it looks like the typo had been overlooked for a while.

**Comment by SciFiDryer** [comment]
Not sure I follow on the link. The link from the other website just links to the most recent release - it would have been 2.3 yesterday. As soon as 2.4 was posted it would be 2.4.

If you are cloning the project as opposed to launching the binary from the jar, the binaries will need to be built. I build them with the NetBeans IDE. When NetBeans builds the binaries, they go to the dist subdirectory, so this could be why. If the project is cloned but not built no jar file will exist.

**Comment by Pratched** [comment]
Yeah didnt explain that to well, doesnt matter however. 

Thanks for clearing things up. Everything works well!
