### ISSUE TITLE
Function Code 16 (0x10) Preset Multiple Registers mislabeled

### ISSUE THREAD

**Issue by Pratched** [SciFiDryer/ModbusMechanic#14]
Not sure how interesting this would be, but I myself would use the Functioncode 0x17 and (0x10) as well.
However I understand, that there might be several other codes with higher priority.

**Comment by SciFiDryer** [comment]
The hex and decimal number for the second function don't match up. It would either be FC 17 (0x11) Report Slave ID or FC 16 (0x10) Preset Multiple Registers, which is already implemented but labeled wrong in the GUI.

As for FC 23 Read/Write Multiple registers, this falls outside the scope of what the GUI is intended to do. The GUI is for either reading or writing values individually to test or view different registers. There would never be a need to batch read and write from the GUI, at least in its current state. FC 23 would be more of a programmatic use. It is implemented in the underlying jlibmodbus library though.

**Comment by SciFiDryer** [comment]
Assuming that the second function code in this request refers to 0x10 Preset Multiple Registers. This is a confirmed bug where it is mislabeled in the GUI.

**Comment by SciFiDryer** [comment]
The label has been updated in 26ee4ad.
