### ISSUE TITLE
[RTU] Allow for higher baud

### ISSUE THREAD

**Issue by ssarna1** [SciFiDryer/ModbusMechanic#17]
**Describe the bug**
I'm using 115200 baud rate, which is not possible to set in ModbusMechanic

**To Reproduce**
1. Go to ModbusMechanic
2. Click on Baud
3. Scroll down
4. See 57600 as max baud

**Expected behavior**
See higher baud settings
**Screenshots**
![obraz](https://user-images.githubusercontent.com/4578755/230771146-9789e078-d5c6-44e1-a5eb-3b06d180d01f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Version 22.04

**Java Runtime Version**
11.0.18

**Additional context**
n/a

**Comment by SciFiDryer** [comment]
Hello, this is a good suggestion. 15200 is the highest baud rate supported by the underlying library so it should be available on the GUI too. 115200 baud rate has been added to the menus in 2327dc4.

**Comment by SciFiDryer** [comment]
The higher baud rate is available in version 2.7 released today. My initial tests of the higher baud passed but if you notice any problems please let me know. I will close the issue in a few days.
