### ISSUE TITLE
Using hide zero option also hides negative Float entries

### ISSUE THREAD

**Issue by kommando828** [SciFiDryer/ModbusMechanic#21]
In the register scanner when you select the 'Hide Zero Value Registers' option not only Zero value registers are hidden but also some registers where the value is negative. See attached screenshots, the Float with negative values are hidden.
![Screenshot (5)](https://github.com/SciFiDryer/ModbusMechanic/assets/32205016/22498757-8386-4484-9ab2-f86c644e6719)
![Screenshot (4)](https://github.com/SciFiDryer/ModbusMechanic/assets/32205016/e510122e-b383-4f9e-a9f4-f172678b5f81)

**Comment by SciFiDryer** [comment]
Thanks for reporting these kinds of issues. Testing feedback from the community is very helpful. This is fixed in e4ac86f.

**Comment by SciFiDryer** [comment]
This fix is built in to version 3.0 which has just been released. There is also a search filter to find specific register values.

**Comment by kommando828** [comment]
Ver 3.0 tested and confirmed as working, thanks for sorting the issue.
