### ISSUE TITLE
Linux - show only active ports

### ISSUE THREAD

**Issue by ijash** [SciFiDryer/ModbusMechanic#3]
Hi,

i just want to inform, it's working on linux.
`linux mint 19.3 Cinnamon.`

some enhancements can be made, such as listing only active serial (ttyS* is all listed). 

thank you for the software.

**Comment by SciFiDryer** [comment]
Good suggestion, Windows only shows active ports. I will check to see if the serial library supports this on Linux.

**Comment by SciFiDryer** [comment]
A filter has been added in 9058f4b to hide tty serial ports on platforms where they exist, such as Linux. This will make it into binary form with the next release or is available immediately from master.
