### ISSUE TITLE
USB serial ports Linux

### ISSUE THREAD

**Issue by awalsum** [SciFiDryer/ModbusMechanic#4]
I have a USB modbus stick that places the tty file in /dev/serial. When I select RTU and want to select the correct serial port, I only get to chose from the ones listed under /dev/, so my USB dongle is not detected.

When using my USB dongle with it's file under /dev/serial in Domoticz, it has no problems being recognised.

**Comment by SciFiDryer** [comment]
Is "display tty serial ports" next to the RTU radio button checked? This option should only hide the serial tty ports, but if the driver presented an atypical name like ttyserialusb or something it may be hiding it from the menu.

The serial library uses the /proc/tty/drivers file to determine prefixes of serial ports registered with the kernel to show. If you don't have any luck with the checkbox, could you post the contents of this file with the USB stick plugged in?

**Comment by awalsum** [comment]
Thanks for your quick reply.
I have the checkbox checked, but it isn't showing. The file is located in /dev/serial/by-id and is named usb-1a86_USB2.0-Ser_-if00-port0

If I open the properties of this file, I see that it shows Link target: ../../ttyUSB0

The contents of the /proc/tty/drivers file is:

/dev/tty             /dev/tty        5       0 system:/dev/tty
/dev/console         /dev/console    5       1 system:console
/dev/ptmx            /dev/ptmx       5       2 system
/dev/vc/0            /dev/vc/0       4       0 system:vtmaster
usbserial            /dev/ttyUSB   188 0-511 serial
ttyprintk            /dev/ttyprintk   5       3 console
max310x              /dev/ttyMAX   204 209-224 serial
serial               /dev/ttyS       4 64-111 serial
pty_slave            /dev/pts      136 0-1048575 pty:slave
pty_master           /dev/ptm      128 0-1048575 pty:master
unknown              /dev/tty        4 1-63 console

**Comment by SciFiDryer** [comment]
It looks like that model usb to serial adapter uses the usbserial module. I would expect ttyUSB0 to show up on the port menu. I have an adapter that also uses the usbserial module and I was not able to reproduce the problem. Here is what I did.

1. Plug in usb adapter and wait for ttyUSB0 to show up in /dev
2. **As root** launch ModbusMechanic

If ModbusMechanic is launched before the usb adapter is plugged in the list of serial adapters may not be current. Also, some distributions do not allow desktop users to write to serial port devices by default, that could be a cause. If I run as a normal user I get PortInUseException.

Failing the steps above there might be something distribution-specific that is causing the issue. I'll leave this issue open in case we need to collect distribution specific information.

As a last resort workaround, you could try renaming the ttyUSB0 device to a device with a ttyS prefix to get around whatever might be preventing it from showing up on the list.
`mv /dev/ttyUSB0 /dev/ttySUSB`
Plus checking "display tty serial ports" should be a workaround, but given the serial port is registered in the normal place this shouldn't be necessary under normal circumstances. Note that by running this workaround anything that looks for the port in its "normal" place might be disrupted.

**Comment by awalsum** [comment]
I got it working now. Root privilege was the problem. I changed the permissions of ttyUSB0 to read and write, and the tool is working. Thanks for pointing me in the right direction.

**Comment by SciFiDryer** [comment]
I'll make the error message more descriptive for future users that may not be running with enough privileges on linux. Just to be clear, was the ttyUSB0 port visible but not usable when running as a normal user, or did it not show up on the menu at all?

**Comment by awalsum** [comment]
The ttyUSB0 port was visible but I was getting a PortInUseException error. After changing permissions to the file ttyUSB0 for other to read/write, the error was gone and tool worked.

**Comment by SciFiDryer** [comment]
In 6e9db3b I've added a more instructive error message also pointing to permissions as a cause for future users. Thanks for reporting the issue.
